src/Entity/Education.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\EducationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;

#[ORM\Entity(repositoryClass: EducationRepository::class)]
class Education
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id;

    #[ORM\Column(length: 255)]
    private ?string $course = null;

    #[ORM\Column(length: 255)]
    private ?string $institution = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ManyToOne(targetEntity: User::class, inversedBy: 'education')]
    #[JoinColumn(name: 'user_id', referencedColumnName: 'id', nullable: false)]
    private ?User $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCourse(): ?string
    {
        return $this->course;
    }

    public function setCourse(string $course): static
    {
        $this->course = $course;

        return $this;
    }

    public function getInstitution(): ?string
    {
        return $this->institution;
    }

    public function setInstitution(string $institution): static
    {
        $this->institution = $institution;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(?\DateTimeInterface $start_date): void
    {
        $this->start_date = $start_date;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): void
    {
        $this->end_date = $end_date;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }
}

src/Entity/Expertise.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\ExpertiseRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;

#[ORM\Entity(repositoryClass: ExpertiseRepository::class)]
class Expertise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id;

    #[ORM\Column(length: 125)]
    private ?string $title = null;

    #[ORM\Column(length: 525)]
    private ?string $description = null;

    #[ORM\Column(length: 55)]
    private ?string $icon_css = null;

    #[ManyToOne(targetEntity: User::class, inversedBy: 'expertise')]
    #[JoinColumn(name: 'user_id', referencedColumnName: 'id', nullable: false)]
    private ?User $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    public function getIconCss(): ?string
    {
        return $this->icon_css;
    }

    public function setIconCss(?string $icon_css): void
    {
        $this->icon_css = $icon_css;
    }
}

src/Controller/HomepageController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\ContactUs;
use App\Entity\User;
use App\Form\ContactUsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class HomepageController extends AbstractController
{
    /**
     * @throws \Exception
     */
    #[Route('/', name: 'app_homepage')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        // Get account details
        $userAccount = $entityManager->getRepository(User::class)->findAll();

        if (1 !== count($userAccount)) {
            throw new \Exception('Error, incorrect user account count returned.');
        }

        // Clean user account assignment
        $userAccount = $userAccount[0];

        // Instantiate contact us form
        $contactUs = new ContactUs();

        // Create contact us form instance
        $contactUsForm = $this->createForm(
            ContactUsType::class,
            $contactUs,
            [
                'action' => $this->generateUrl('app_contact_us'),
                'method' => 'POST',
                'attr' => [
                    'id' => 'contact-us-form',
                ],
            ]
        );

        return $this->render(
            'homepage/index.html.twig',
            [
                'contactUsForm' => $contactUsForm->createView(),
                'userAccount' => $userAccount,
            ]
        );
    }
}

templates/homepage/panels/about.html.twig
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
            <h2>About Me</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <ul role="list" class="info">
                <li role="listitem">
                    <span class="first-block">Full Name:</span><span class="second-block">{{ userAccount.firstname|escape }} {{ userAccount.surname|escape }}</span>
                </li>
                <li role="listitem">
                    <span class="first-block">Location:</span><span class="second-block">{{ userAccount.location|escape }}</span>
                </li>
                <li role="listitem">
                    <span class="first-block">Email:</span><span class="second-block"><a target="_blank" href="mailto:{{ userAccount.email|escape }}?subject=Website enquiry">{{ userAccount.email|escape }}</a></span>
                </li>
                <li role="listitem">
                    <span class="first-block">LinkedIn:</span><span class="second-block"><a target="_blank" href="{{ userAccount.linkedin }}">{{ userAccount.linkedin|replace({'https://www.linkedin.com/in/': ''})|escape }}</a></span>
                </li>
                <li>
                    <span class="first-block">GitHub:</span><span class="second-block"><a target="_blank" href="{{ userAccount.github }}">{{ userAccount.github|replace({'https://github.com/': ''})|escape }}</a></span>
                </li>
            </ul>
        </div>
        <div class="col-md-8">
            <h2>Hello There!</h2>
            {{ userAccount.aboutMe|raw }}
            <h3>Work Philosophy</h3>
            {{ userAccount.philosophy|raw }}
        </div>
    </div>
</div>

templates/homepage/panels/details.html.twig
<div class="overlay"></div>
<div class="container">
    <div class="row animate-box">
        <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
            <h2>Hire Me!</h2>
            <p>If you need any advice or want to collaborate on work, please feel free to reach out at any time.</p>
            <p><a href="#contact-us-section" class="btn btn-default btn-lg">Contact Me!</a></p>
        </div>
    </div>
</div>

templates/homepage/panels/expertise.html.twig
<div class="container">
    <div class="services-padding">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>Areas of expertise</h2>
            </div>
        </div>
        {% if userAccount.expertise|length == 0 %}
            <div class="alert alert-danger" role="alert">Please add your expertise</div>
        {% endif %}
        <div class="row">
            {% for expertise in userAccount.expertise|slice(0,3) %}
            <div class="col-md-4 text-center">
                <div class="feature-left">
                <span class="icon">
                    <i class="icon-{{ expertise.iconCss|escape }}"></i>
                </span>
                    <div class="feature-copy">
                        <h3>{{ expertise.title|escape }}</h3>
                        <p>{{ expertise.description|escape }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row">
            {% for expertise in userAccount.expertise|slice(3,6) %}
            <div class="col-md-4 text-center">
                <div class="feature-left">
                <span class="icon">
                    <i class="icon-{{ expertise.iconCss|escape }}"></i>
                </span>
                    <div class="feature-copy">
                        <h3>{{ expertise.title|escape }}</h3>
                        <p>{{ expertise.description|escape }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/homepage/panels/footer.html.twig
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>&copy; {{ "now"|date("Y") }} Joseph James Smyth Portfolio and Resume</p>
        </div>
    </div>
</div>

templates/homepage/panels/header.html.twig
<div class="overlay"></div>
<div id="user-profile">
    <div class="display-t js-fullheight">
        <div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
            <div class="profile-thumb" style="background: url({{ asset('images/user-3.jpg') }});"></div>
            <div class="profile-name text-center">
                <h1><span>{{ userAccount.firstname|escape }} {{ userAccount.surname|escape }}</span></h1>
                <h2 class="mb-4"><span>{{ userAccount.jobTitle|escape }}</span></h2>
                <ul role="list" class="fh5co-social-icons">
                    {# <li><a href="#"><i class="icon-twitter2"></i></a></li> #}
                    {# <li><a href="#"><i class="icon-facebook2"></i></a></li> #}
                    <li>
                        <a aria-label="linkedin" target="_blank" href="{{ userAccount.linkedin|escape }}"><i class="icon-linkedin2"></i></a>
                    </li>
                    {# <li role="listitem"><a href="#"><i class="icon-dribbble2"></i></a></li> #}
                </ul>
            </div>
        </div>
    </div>
</div>

templates/homepage/panels/resume.html.twig
<div class="container">
    <div class="row animate-box">
        <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
            <h2>My Resume</h2>
            {% if userAccount.resume|length == 0 %}
                <div class="alert alert-danger" role="alert">Please add your Resume</div>
            {% endif %}
            <div class="custom-btn-group mt-4">
                {% for resume in userAccount.resume %}
                    <a href="{{ asset('uploads/resume/') }}{{ resume.resumeFilename|escape }}" class="btn mr-lg-2 custom-btn" download="{{ resume.resumeFilename|escape }}">
                        <i class="uil uil-file-alt"></i>
                        Download Resume
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-md-offset-0">
            <ul role="list" class="timeline">
                <li class="timeline-heading text-center animate-box">
                    <div><h3>Work Experience</h3></div>
                </li>
                {% if userAccount.workExperience|length == 0 %}
                    <div class="alert alert-danger" role="alert">Please add your work experience</div>
                {% endif %}
                {% for workExperience in userAccount.workExperience|reverse %}
                    {% set listPosition = 'animate-box timeline-unverted' %}
                    {% if (loop.index is even) %}
                        {% set listPosition = 'animate-box timeline-inverted' %}
                    {% endif %}
                    <li class="{{ listPosition|escape }}">
                        <div class="timeline-badge"><i class="icon-suitcase"></i></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h3 class="timeline-title">{{ workExperience.title|escape }}</h3>
                                <span class="company">{{ workExperience.business|escape }} - {{ workExperience.startDate|date('F')|escape }} {{ workExperience.startDate|date('Y')|escape }} - {% if loop.first %}Current{% else %}{{ workExperience.endDate|date('F')|escape }} {{ workExperience.endDate|date('Y')|escape }}{% endif %}</span>
                            </div>
                            <div class="timeline-body">
                                <p>{{ workExperience.description|escape }}</p>
                            </div>
                        </div>
                    </li>
                {% endfor %}
                <br>
                <li class="timeline-heading text-center animate-box">
                    <div><h3>Education</h3></div>
                </li>
                {% if userAccount.education|length == 0 %}
                    <div class="alert alert-danger" role="alert">Please add your education</div>
                {% endif %}
                {% for education in userAccount.education|reverse %}
                    {% set listPosition = 'animate-box timeline-unverted' %}
                    {% if (loop.index is even) %}
                        {% set listPosition = 'animate-box timeline-inverted' %}
                    {% endif %}
                    <li class="{{ listPosition|escape }}">
                        <div class="timeline-badge"><i class="icon-graduation-cap"></i></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h3 class="timeline-title">{{ education.course|escape }}</h3>
                                <span class="company">{{ education.institution|escape }} - {{ education.startDate|date('F')|escape }} {{ education.startDate|date('Y')|escape }} - {{ education.endDate|date('F')|escape }} {{ education.endDate|date('Y')|escape }}</span>
                            </div>
                            <div class="timeline-body">
                                <p>{{ education.title|escape }}</p>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/homepage/panels/skills.html.twig
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
            <h2>Skills</h2>
        </div>
    </div>
    <div class="row">
        {% if userAccount.skills|length == 0 %}
            <div class="alert alert-danger" role="alert">Please add your skills</div>
        {% endif %}
        {% for skill in userAccount.skills|sort((a, b) => b.percentage <=> a.percentage)|slice(0,4) %}
            <div class="col-md-3 col-sm-6 text-center">
                <svg data-title="{{ skill.title|upper|escape }}" height="250" viewBox="0 0 160 200"
                     class="circular-progress-1" preserveAspectRatio="xMaxYMax meet">
                    <foreignobject class="node" x="{{ skill.foreignObjectX|escape }}"
                                   y="{{ skill.foreignObjectY|escape }}" width="{{ skill.foreignObjectWidth|escape }}"
                                   height="{{ skill.foreignObjectHeight|escape }}">
                        <span>{{ skill.title|upper|escape }}<br>{{ skill.percentage|escape }}%</span>
                    </foreignobject>
                    <circle class="bg"></circle>
                    <circle class="fg"></circle>
                </svg>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        {% for skill in userAccount.skills|sort((a, b) => b.percentage <=> a.percentage)|slice(5,50) %}
            {% set progressColour = 'progress-bar-1' %}
            {% if skill.percentage >= 85 %}
                {% set progressColour = 'progress-bar-2' %}
            {% elseif skill.percentage >= 75 %}
                {% set progressColour = 'progress-bar-3' %}
            {% elseif skill.percentage >= 55 %}
                {% set progressColour = 'progress-bar-5' %}
            {% endif %}
            <div class="col-md-4">
                <div class="progress-wrap">
                    <h3>
                        <span class="name-left">{{ skill.title|escape }}</span>
                        <span class="value-right">{{ skill.percentage|escape }}%</span>
                    </h3>
                    <div class="progress">
                        <div class="progress-bar {{ progressColour|escape }} progress-bar-striped active"
                             role="progressbar"
                             aria-label="{{ skill.percentage|lower|escape }}"
                             aria-valuenow="{{ skill.percentage|escape }}"
                             aria-valuemin="0" aria-valuemax="100" style="width:{{ skill.percentage|escape }}%">
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>